# Generated by Django 4.2.21 on 2025-05-10 13:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Tests.question')),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None, verbose_name='Варіанти відповідей')),
                ('correct_choice', models.IntegerField(verbose_name='Індекс правильної відповіді')),
            ],
            bases=('Tests.question',),
        ),
    ]
