# Generated by Django 4.2.21 on 2025-05-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0002_choicequestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textquestion',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='textquestion',
            name='correct_choice',
        ),
        migrations.AddField(
            model_name='textquestion',
            name='correct_answer',
            field=models.TextField(default='', verbose_name='Правильна відповідь'),
            preserve_default=False,
        ),
    ]
